### Matplotlib-Style Data Sampling Tricks

In [1]:
import numpy as np

x = [1, 2]
y = [3, 4, 5]

xx1, yy1 = np.meshgrid(x, y)
print(xx1)
print(yy1)
print(xx1 + yy1)

[[1 2]
 [1 2]
 [1 2]]
[[3 3]
 [4 4]
 [5 5]]
[[4 5]
 [5 6]
 [6 7]]


In [2]:
xx2, yy2 = np.atleast_2d(x, y)
print(xx2)
print(yy2)

print(xx2.T + yy2)
print(xx2 + yy2.T)

[[1 2]]
[[3 4 5]]
[[4 5 6]
 [5 6 7]]
[[4 5]
 [5 6]
 [6 7]]


In [3]:
xx3, yy3 = np.mgrid[1:3, 3:6]
print(xx3)
print(yy3)

[[1 1 1]
 [2 2 2]]
[[3 4 5]
 [3 4 5]]


In [4]:
xx4, yy4 = np.ogrid[1:3, 3:6]
print(xx4)
print(yy4)

[[1]
 [2]]
[[3 4 5]]


### Numpy-Style Data Sampling Tricks

In [5]:
xy5 = np.column_stack([
    np.repeat(x, len(y)),
    np.tile(y, len(x)),
])
print(xy5)

[[1 3]
 [1 4]
 [1 5]
 [2 3]
 [2 4]
 [2 5]]


### Numpy Stacking

In [28]:
import numpy as np

x2 = np.array([1, 2, 3])
y2 = np.array([4, 5, 6])
z2_1 = np.stack((x2,y2), axis=1)
z2_2 = z2_1 + 1
print(z2_1)
print(z2_2)
print('----------')
print(np.concatenate((z2_1, z2_2), axis=1))
print(np.stack((z2_1, z2_2), axis=1))
z2_3 = np.concatenate((z2_1, z2_2), axis=0)
print(np.split(z2_3, 3))

[[1 4]
 [2 5]
 [3 6]]
[[2 5]
 [3 6]
 [4 7]]
----------
[[1 4 2 5]
 [2 5 3 6]
 [3 6 4 7]]
[[[1 4]
  [2 5]]

 [[2 5]
  [3 6]]

 [[3 6]
  [4 7]]]
[array([[1, 4],
       [2, 5]]), array([[3, 6],
       [2, 5]]), array([[3, 6],
       [4, 7]])]


### Miscellaneous

In [6]:
""" one-hot array encoding or generation. """
a1 = np.array([0, 1, 2, 3])
b1 = np.zeros((a1.size, a1.max() + 1))
print(b1)
b1[np.arange(a1.size), a1] = 1
print(b1)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [7]:
a2 = np.identity(4)
print(a2)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [8]:
""" `@` operator """
a = np.arange(6).reshape(3,2,1)
b = np.arange(12).reshape(3,1,4)
print(a)
print(b)
print('-----------------')
print(a @ b)
print(a.dot(b))

[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]
[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]
-----------------
[[[ 0  0  0  0]
  [ 0  1  2  3]]

 [[ 8 10 12 14]
  [12 15 18 21]]

 [[32 36 40 44]
  [40 45 50 55]]]
[[[[ 0  0  0  0]
   [ 0  0  0  0]
   [ 0  0  0  0]]

  [[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]]


 [[[ 0  2  4  6]
   [ 8 10 12 14]
   [16 18 20 22]]

  [[ 0  3  6  9]
   [12 15 18 21]
   [24 27 30 33]]]


 [[[ 0  4  8 12]
   [16 20 24 28]
   [32 36 40 44]]

  [[ 0  5 10 15]
   [20 25 30 35]
   [40 45 50 55]]]]


In [9]:
a = np.array([
    [
        [-1, -1,  1,  1.],
        [-1,  1, -1,  1]
    ],
    [
        [ 0.5, 0.11920292,  0.88079708,  0.5       ],
        [ 0.5, 0.88079708,  0.11920292,  0.5       ]
    ]
])
print(a[0:2][:][1])
print(a[0:2, :, 1])

[[ 0.5         0.11920292  0.88079708  0.5       ]
 [ 0.5         0.88079708  0.11920292  0.5       ]]
[[-1.          1.        ]
 [ 0.11920292  0.88079708]]


In [41]:
import numpy as np

a5 = np.array([
    [0, 1],
    [2, 3]
])

print(np.add(a5, 1, where=[0,1]))
print(np.add(a5, 1, where=[[0,1]]))

[[0 2]
 [2 4]]
[[0 2]
 [2 4]]
