### Matplotlib-Style Data Sampling Tricks

TODO: https://devdocs.io/numpy~1.14/routines.indexing

In [139]:
import numpy as np

x = [1, 2]
y = [3, 4, 5]

"""                 → → →
                    | ↖ |
sampling direction: → → →
"""
xx1, yy1 = np.meshgrid(x, y)
print(xx1)
print(yy1)
print(xx1 + yy1)

[[1 2]
 [1 2]
 [1 2]]
[[3 3]
 [4 4]
 [5 5]]
[[4 5]
 [5 6]
 [6 7]]


In [2]:
xx2, yy2 = np.atleast_2d(x, y)
print(xx2)
print(yy2)

print(xx2.T + yy2)
print(xx2 + yy2.T)

[[1 2]]
[[3 4 5]]
[[4 5 6]
 [5 6 7]]
[[4 5]
 [5 6]
 [6 7]]


In [142]:
"""                 ↑---↑---->
                    ↑ ↘ ↑---->
sampling direction: ↑---↑---->
"""
xx3, yy3 = np.mgrid[1:3, 3:6]
print(xx3)
print(yy3)
print(xx3 + yy3)

# xy3 = np.mgrid[-1:1:2/7, -1:1:2/3]
# print(xy3)

[[1 1 1]
 [2 2 2]]
[[3 4 5]
 [3 4 5]]
[[4 5 6]
 [5 6 7]]


In [143]:
""" ditto """
xx4, yy4 = np.ogrid[1:3, 3:6]
print(xx4)
print(yy4)
print(xx4 + yy4)

[[1]
 [2]]
[[3 4 5]]
[[4 5 6]
 [5 6 7]]


In [177]:
""" ditto """
xx6, yy6 = np.ix_(x,y)
print(xx6)
print(yy6)
print(xx6 + yy6)

[[1]
 [2]]
[[3 4 5]]
[[4 5 6]
 [5 6 7]]


In [176]:
""" ditto """
xx5, yy5 = np.indices((2,3))
print(xx5)
print(yy5)
print(xx5 + yy5)

[[0 0 0]
 [1 1 1]]
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [1 2 3]]


### Numpy-Style Data Sampling Tricks

In [5]:
xy5 = np.column_stack([
    np.repeat(x, len(y)),
    np.tile(y, len(x)),
])
print(xy5)

[[1 3]
 [1 4]
 [1 5]
 [2 3]
 [2 4]
 [2 5]]


### Array Joining
| method name | input requirements | create new axis? |
| - | - | - |
| `[v\|h\|d]stack` | similar | not necessary |
| `[row\|column]_stack` | ditto aproximately |
| `concatenate`/`append` | **same except one dim** | no |
| `stack` | **must same shape** | **force** |
| `insert` | `slice=values` **is valid** | **cannot** |

[h|v|d]stack & [row|column]_stack in 2D

In [15]:
import numpy as np

a = np.arange(4).reshape(2,2)
b = np.array([-1] * 2)
ab = np.row_stack((a,b))
print('0-------\n', ab)

ab1 = np.column_stack((a,b))
print('1-------\n', ab1)

ab2 = np.vstack((a,b))
print('2-------\n', ab2)
# error! must same ndim.
# ab3 = np.hstack((a,b))

ab3 = np.c_[a,b]
print('3-------\n', ab3)

# error! must same ndim.
# ab5 = np.r_[a, b]

0-------
 [[ 0  1]
 [ 2  3]
 [-1 -1]]
1-------
 [[ 0  1 -1]
 [ 2  3 -1]]
2-------
 [[ 0  1]
 [ 2  3]
 [-1 -1]]
3-------
 [[ 0  1 -1]
 [ 2  3 -1]]
4-------
 [[ 0  1]
 [ 2  3]
 [-1 -1]]


[h|v|d]stack & [row|column]_stack in 3D

In [22]:
import numpy as np

a = np.arange(0,12).reshape(3,2,2)
b = np.arange(2,8).reshape(3,2)
print(a)
print(b)
# error! must same ndim.
# ab = np.column_stack((a,b))
# ab1 = np.row_stack((a.reshape(2,3,2), b))
a = np.arange(0,6).reshape(3,2)
b = np.arange(2,5).reshape(3)
ab2 = np.column_stack([a,b])
print(ab2)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
[[2 3]
 [4 5]
 [6 7]]
[[0 1 2]
 [2 3 3]
 [4 5 4]]


In [18]:
import numpy as np

a = np.arange(8).reshape(2,2,2)
b = np.arange(4).reshape(2,2)
print(a)
print(b)
# error! must same ndim.
# ab = np.vstack((a,b))
# ab1 = np.hstack((a,b))
# error! must same shape.
ab2 = np.stack((a,b), 1)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[0 1]
 [2 3]]


ValueError: all input arrays must have the same shape

In [155]:
import numpy as np

a = np.arange(8).reshape(2,4)
b = np.arange(5,9)
ab = np.vstack((a,b))
print('0------\n', ab)
ab1 = np.vstack((a,b.reshape(1,4)))
print('1------\n', ab1)
ab2 = np.vstack((a.reshape(2,2,2),b.reshape(1,2,2)))
print('2------\n', ab4)
# error!
# ab4 = np.vstack((a.reshape(2,2,2),b.reshape(2,1,2)))
ab5 = np.hstack((a.reshape(2,2,2),b.reshape(2,1,2)))
print('5------\n', ab5)

0------
 [[0 1 2 3]
 [4 5 6 7]
 [5 6 7 8]]
1------
 [[0 1 2 3]
 [4 5 6 7]
 [5 6 7 8]]
2------
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]

 [[5 6]
  [7 8]]]
5------
 [[[0 1]
  [2 3]
  [5 6]]

 [[4 5]
  [6 7]
  [7 8]]]


Stack

In [148]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
ab = np.stack((a,b), 0)
print('0----------\n', ab)

ab1 = np.stack((a,b), axis=1)
ab2 = ab1 + 1
print('1----------')
print(ab1)
print(ab2)

print('2----------')
print(np.concatenate((ab1, ab2), axis=1))
print(np.stack((ab1, ab2), axis=1))
ab3 = np.concatenate((ab1, ab2), axis=0)
print(np.split(ab3, 3))

0----------
 [[1 2 3]
 [4 5 6]]
1----------
[[1 4]
 [2 5]
 [3 6]]
[[2 5]
 [3 6]
 [4 7]]
2----------
[[1 4 2 5]
 [2 5 3 6]
 [3 6 4 7]]
[[[1 4]
  [2 5]]

 [[2 5]
  [3 6]]

 [[3 6]
  [4 7]]]
[array([[1, 4],
       [2, 5]]), array([[3, 6],
       [2, 5]]), array([[3, 6],
       [4, 7]])]


Newing axis with custom data.

In [163]:
import numpy as np

"""
method 1: np.newaxis + np.insert
method 2: np.stack
"""
a = np.array([
    [0.3,0.2], [0.6, 0.5], [-0.9, -1.1]
])
# print('0--------\n', a)

a1 = a.copy()
a1[:, 0] = np.arange(3)[:]
print('1--------\n', a1)

a2 = np.insert(
    a[:, :], 
    0, # (3,)
    values=np.arange(3)[:], # (3,)
    axis=-1
)
print('2--------\n', a2)

a3 = np.stack([
    np.broadcast_to(range(3),(2,3)).T, a 
], axis=2)
print('3--------\n', a3)

a4 = np.insert(
    a[:, :, np.newaxis], 
    0, 
    values=np.arange(3)[:, np.newaxis], 
    axis=-1
)
print('4-------\n', a4)

print(np.transpose(a4, (1, 0, 2)))

a5 = np.append(a, [range(2)], 0)
print('5--------\n', a5)

1--------
 [[ 0.   0.2]
 [ 1.   0.5]
 [ 2.  -1.1]]
2--------
 [[ 0.   0.3  0.2]
 [ 1.   0.6  0.5]
 [ 2.  -0.9 -1.1]]
3--------
 [[[ 0.   0.3]
  [ 0.   0.2]]

 [[ 1.   0.6]
  [ 1.   0.5]]

 [[ 2.  -0.9]
  [ 2.  -1.1]]]
4-------
 [[[ 0.   0.3]
  [ 0.   0.2]]

 [[ 1.   0.6]
  [ 1.   0.5]]

 [[ 2.  -0.9]
  [ 2.  -1.1]]]
[[[ 0.   0.3]
  [ 1.   0.6]
  [ 2.  -0.9]]

 [[ 0.   0.2]
  [ 1.   0.5]
  [ 2.  -1.1]]]
5--------
 [[ 0.3  0.2]
 [ 0.6  0.5]
 [-0.9 -1.1]
 [ 0.   1. ]]


### Miscellaneous

In [7]:
a2 = np.identity(4)
print(a2)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [32]:
import numpy as np

b = np.zeros((5,5))
print(b)
print('-----------------')
b[np.diag_indices(3)] = 100
print(b)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
-----------------
[[ 100.    0.    0.    0.    0.]
 [   0.  100.    0.    0.    0.]
 [   0.    0.  100.    0.    0.]
 [   0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.]]


In [8]:
""" `@` operator """
a = np.arange(6).reshape(3,2,1)
b = np.arange(12).reshape(3,1,4)
print(a)
print(b)
print('-----------------')
print(a @ b)
print(a.dot(b))

[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]
[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]
-----------------
[[[ 0  0  0  0]
  [ 0  1  2  3]]

 [[ 8 10 12 14]
  [12 15 18 21]]

 [[32 36 40 44]
  [40 45 50 55]]]
[[[[ 0  0  0  0]
   [ 0  0  0  0]
   [ 0  0  0  0]]

  [[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]]


 [[[ 0  2  4  6]
   [ 8 10 12 14]
   [16 18 20 22]]

  [[ 0  3  6  9]
   [12 15 18 21]
   [24 27 30 33]]]


 [[[ 0  4  8 12]
   [16 20 24 28]
   [32 36 40 44]]

  [[ 0  5 10 15]
   [20 25 30 35]
   [40 45 50 55]]]]


In [9]:
a = np.array([
    [
        [-1, -1,  1,  1.],
        [-1,  1, -1,  1]
    ],
    [
        [ 0.5, 0.11920292,  0.88079708,  0.5       ],
        [ 0.5, 0.88079708,  0.11920292,  0.5       ]
    ]
])
print(a[0:2][:][1])
print(a[0:2, :, 1])

[[ 0.5         0.11920292  0.88079708  0.5       ]
 [ 0.5         0.88079708  0.11920292  0.5       ]]
[[-1.          1.        ]
 [ 0.11920292  0.88079708]]


In [166]:
import numpy as np

a = np.array([
    [0, 1],
    [2, 3]
])

print(np.add(a, 1, where=[0,1]))
print(np.add(a, 1, where=[[0,1]]))
print(a+[0, 1])
a1 = a.copy()
a1[:, 1] += 1
print(a1)

[[0 2]
 [2 4]]
[[0 2]
 [2 4]]
[[0 2]
 [2 4]]
[[0 2]
 [2 4]]


In [167]:
import numpy as np

a = np.arange(6).reshape(3,2,1)
b = np.arange(3,6).reshape(3,1)
print('0--------\n', a)
print(b)

a1 = a.copy()
a1[:, :, 0] = b
print('1--------\n', a1)

a2 = a.reshape(3,2)
a2[:, :] = b
print('2--------\n', a2)

0--------
 [[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]
[[3]
 [4]
 [5]]
1--------
 [[[3]
  [3]]

 [[4]
  [4]]

 [[5]
  [5]]]
2--------
 [[3 3]
 [4 4]
 [5 5]]


In [99]:
""" broadcasting when assigning will not change dims of original arr. """
import numpy as np

a = np.arange(3)
b = np.array(4).reshape(1,1)
print('0-------\n', a)
print(b)

a1 = a.copy()
a1[:] = b
print('1-------\n', a1)

a2 = a.reshape(1,3)
a2[:] = b
print('2-------\n', a2)

a3 = a.copy()
b1 = b.reshape(1,1,1)
a3[:] = b1
print('3-------\n', a3)

0-------
 [0 1 2]
[[4]]
1-------
 [4 4 4]
2-------
 [[4 4 4]]
3-------
 [4 4 4]


In [11]:
import numpy as np

A = np.array([[1,2], [3, 9]])
count = np.zeros(10)
# count[A]
print(count[(A)])

[[ 0.  0.]
 [ 0.  0.]]


### Indexing

In [6]:
""" one-hot array encoding or generation. """
a1 = np.array([0, 1, 2, 3])
b1 = np.zeros((a1.size, a1.max() + 1))
print(b1)
b1[np.arange(a1.size), a1] = 1
print(b1)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [180]:
import numpy as np

a = np.array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])
print(np.argmax(a,1)==0)
print(np.where(np.argmax(a,1)==0))
print(a[np.argmax(a,1)==0])
print(a[np.where(np.argmax(a,1)==0)])

[ True False False False  True]
(array([0, 4]),)
[[ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]]
[[ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]]


In [183]:
import numpy as np

a = np.array([1,2,3,4,5])
# error!
# a = range(1,6)
print(a[a % 2 == 0])

[2 4]


In [204]:
import numpy as np

a = np.arange(10)
l = [2,4,6]
print('--------')



print(np.isin(a, l))
print(np.where(np.isin(a, l)))
print('1-------')
print(a[np.isin(a, l)])
print(a[np.where(np.isin(a, l))])
print(list(filter(lambda _: _ not in l, a)))
# np.where(a.any() not in np.array([2,4,6]))

--------
[False False  True False  True False  True False False False]
(array([2, 4, 6]),)
1-------
[2 4 6]
[2 4 6]
[0, 1, 3, 5, 7, 8, 9]


True